version: "3"

services:
  server:
    build: ./issue-tracker-server
    ports:
      - "3001:3001"
    volumes:
      - ./issue-tracker-server:/app
    restart: always

  client:
    build: ./issue-tracker-client
    ports:
      - "3000:80"
    volumes:
      - ./issue-tracker-client:/app
    restart: always
